# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: mongo
    restart: always
    volumes:
      #- ${WEBAPP_STORAGE_HOME}/site:/data/db
      - /Catalog/mongo_data:/data/db
    ports:
      - "27017:27017"

  basketdb:
    container_name: basketdb
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"    
  
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "8000:8000" 
      - "9000:9000"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /Services/portainer_data:/data

  discountdb:
    container_name: discountdb
    image: postgres
    restart: always
    ports:
      - "5432:5432"  
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDB
    volumes: 
      - /Discount/postgres_data:/var/lib/postgres/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5055:80"  
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    volumes: 
      - /Discount/pgadmin_data:/root/.pgadmin     

  catalogapi:
    image: catalogapi
    build:
      context: Catalog
      dockerfile: Dockerfile
    ports:
        - "8001:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - “CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017”    
    depends_on:
        - catalogdb
    volumes:
        - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
        - ${HOME}/.aspnet/https:/root/.aspnet/https/

  basketapi:
    image: basketapi
    build:
      context: Basket
      dockerfile: Dockerfile
    ports:
      - 8002:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - “CacheSettings:ConnectionString=basketdb:6379"    
    depends_on:
        - basketdb

    
  discountapi:
    image: discountapi
    build:
      context: Discount
      dockerfile: Dockerfile
    ports:
      - 8003:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDB;User ID=admin;Password=admin1234;"    
    depends_on:
      - discountdb